// <auto-generated />
using System;
using DiagnosticoMedico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiagnosticoMedico.Migrations
{
    [DbContext(typeof(DiagnosticoMedicoContext))]
    partial class DiagnosticoMedicoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Examen", b =>
                {
                    b.Property<int>("ExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExamenId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExamenCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereAyuno")
                        .HasColumnType("boolean");

                    b.Property<int>("TiempoProcesamiento")
                        .HasColumnType("integer");

                    b.HasKey("ExamenId");

                    b.ToTable("Examen");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Informe", b =>
                {
                    b.Property<int>("InformeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InformeId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<string>("InformeCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacionesGenerales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdenLaboratorioId")
                        .HasColumnType("integer");

                    b.HasKey("InformeId");

                    b.HasIndex("OrdenLaboratorioId");

                    b.ToTable("Informe");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Muestra", b =>
                {
                    b.Property<int>("MuestraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MuestraId"));

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaRecoleccion")
                        .HasColumnType("date");

                    b.Property<string>("MuestraCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoMuestra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Volumen")
                        .HasColumnType("double precision");

                    b.HasKey("MuestraId");

                    b.ToTable("Muestra");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.OrdenExamen", b =>
                {
                    b.Property<int>("OrdenExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenExamenId"));

                    b.Property<string>("AreaLaboratorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoOrdenExamen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExamenId")
                        .HasColumnType("integer");

                    b.Property<int>("MuestraId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer");

                    b.HasKey("OrdenExamenId");

                    b.HasIndex("ExamenId");

                    b.HasIndex("MuestraId");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenExamen");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.OrdenLaboratorio", b =>
                {
                    b.Property<int>("OrdenLaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenLaboratorioId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoOrdenLaboratorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaOrden")
                        .HasColumnType("date");

                    b.Property<string>("MedicoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrdenLaboratorioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PacienteCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAtencion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrdenLaboratorioId");

                    b.ToTable("OrdenLaboratorio");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.ParametroExamen", b =>
                {
                    b.Property<int>("ParametroExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParametroExamenId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExamenId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametroExamenCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMin")
                        .HasColumnType("numeric");

                    b.HasKey("ParametroExamenId");

                    b.HasIndex("ExamenId");

                    b.ToTable("ParametroExamen");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Resultado", b =>
                {
                    b.Property<int>("ResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultadoId"));

                    b.Property<string>("EquipoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaResultado")
                        .HasColumnType("date");

                    b.Property<string>("MuestraCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuestraId")
                        .HasColumnType("integer");

                    b.Property<string>("ParametroExamenCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParametroExamenId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultadoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("ResultadoId");

                    b.HasIndex("MuestraId");

                    b.HasIndex("ParametroExamenId");

                    b.ToTable("Resultado");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.ValidacionResultado", b =>
                {
                    b.Property<int>("ValidacionResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ValidacionResultadoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaValidacion")
                        .HasColumnType("date");

                    b.Property<string>("MedicoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResultadoId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidacionResultadoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ValidacionResultadoId");

                    b.HasIndex("ResultadoId");

                    b.ToTable("ValidacionResultado");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Informe", b =>
                {
                    b.HasOne("DiagnosticoMedico.Dominio.OrdenLaboratorio", "Orden")
                        .WithMany("Informes")
                        .HasForeignKey("OrdenLaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.OrdenExamen", b =>
                {
                    b.HasOne("DiagnosticoMedico.Dominio.Examen", "Examen")
                        .WithMany("OrdenExamenes")
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiagnosticoMedico.Dominio.Muestra", "Muestra")
                        .WithMany("OrdenExamen")
                        .HasForeignKey("MuestraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiagnosticoMedico.Dominio.OrdenLaboratorio", "OrdenLaboratorio")
                        .WithMany("OrdenExamenesOrdenExamenes")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");

                    b.Navigation("Muestra");

                    b.Navigation("OrdenLaboratorio");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.ParametroExamen", b =>
                {
                    b.HasOne("DiagnosticoMedico.Dominio.Examen", "Examen")
                        .WithMany("ParametroExamenes")
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Resultado", b =>
                {
                    b.HasOne("DiagnosticoMedico.Dominio.Muestra", "Muestra")
                        .WithMany("Resultados")
                        .HasForeignKey("MuestraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiagnosticoMedico.Dominio.ParametroExamen", "ParametroExamen")
                        .WithMany("Resultados")
                        .HasForeignKey("ParametroExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muestra");

                    b.Navigation("ParametroExamen");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.ValidacionResultado", b =>
                {
                    b.HasOne("DiagnosticoMedico.Dominio.Resultado", "Resultado")
                        .WithMany("Validaciones")
                        .HasForeignKey("ResultadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Examen", b =>
                {
                    b.Navigation("OrdenExamenes");

                    b.Navigation("ParametroExamenes");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Muestra", b =>
                {
                    b.Navigation("OrdenExamen");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.OrdenLaboratorio", b =>
                {
                    b.Navigation("Informes");

                    b.Navigation("OrdenExamenesOrdenExamenes");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.ParametroExamen", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("DiagnosticoMedico.Dominio.Resultado", b =>
                {
                    b.Navigation("Validaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
